ubc_apsc_helper.settings:
  type: config_object
  label: 'Syndicated canonical url settings'
  mapping:
    ubc_apsc_helper:
      type: mapping
      mapping:
        external_stylesheet_load:
          type: checkbox
          label: 'Load external stylesheet'
        external_stylesheet_url:
          type: text
          label: 'External stylesheet URL'
        external_stylesheet_body_class:
          type: text
          label: 'Additional &lt;body&gt; class'
